apiVersion: batch/v1
kind: CronJob
metadata:
  name: tidal-sync
  namespace: default 
spec:
  schedule: "0 0 * * *" 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: tidal-sync
            image: ghcr.io/shawnux/tidal-sync:latest
            imagePullPolicy: Always
            env:
            - name: SESSION_PATH
              value: "/app/secrets/session.json"
            # --------------------------
            volumeMounts:
            - name: auth-vol
              mountPath: "/app/secrets"
              readOnly: true
          volumes:
          - name: auth-vol
            secret:
              secretName: tidal-session-secret
          restartPolicy: OnFailure