---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: musicbrainz-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: musicbrainz
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: musicbrainz
  template:
    metadata:
      labels:
        app: musicbrainz
    spec:
      containers:
      - name: musicbrainz
        image: lscr.io/linuxserver/musicbrainz:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/New_York"
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: data
          mountPath: /config
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: musicbrainz-data
---
apiVersion: v1
kind: Service
metadata:
  name: musicbrainz
  namespace: default
spec:
  selector:
    app: musicbrainz
  ports:
  - port: 5000
    targetPort: 5000